name: Container Build and Test

on:
  push:
    branches: [ master, main, develop ]
    paths:
      - 'deploy/podman/**'
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/containers.yml'
  pull_request:
    branches: [ master, main, develop ]
    paths:
      - 'deploy/podman/**'
      - 'src/**'
      - 'tests/**'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_PREFIX: ${{ github.repository }}

jobs:
  verify-setup:
    name: Verify Podman Setup
    runs-on: [self-hosted, linux, x64, oracle-linux]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Display versions
        run: |
          podman --version
          buildah --version
          skopeo --version
          echo "Runner: $RUNNER_NAME"
          echo "System: $(uname -a)"
          gcc --version

      - name: Verify rootless support
        run: |
          cd deploy/podman
          ./scripts/verify-rootless.sh || true

  build-dev:
    name: Build Development Image
    runs-on: [self-hosted, linux, x64, oracle-linux]
    needs: verify-setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Clean previous builds
        run: |
          podman rm -f ocserv-modern-dev-build || true
          podman rmi -f localhost/ocserv-modern-dev:latest || true

      - name: Build development image
        run: |
          cd deploy/podman
          chmod +x scripts/build-dev.sh
          IMAGE_NAME=localhost/ocserv-modern-dev IMAGE_TAG=latest ./scripts/build-dev.sh
        timeout-minutes: 30

      - name: Verify image
        run: |
          podman images | grep ocserv-modern-dev
          podman inspect localhost/ocserv-modern-dev:latest

      - name: Test container startup
        run: |
          podman run --rm localhost/ocserv-modern-dev:latest echo "Container started successfully"
          podman run --rm localhost/ocserv-modern-dev:latest wolfssl --version || echo "wolfSSL not in PATH yet"

      - name: Save image
        run: |
          mkdir -p /tmp/images-${{ github.run_id }}
          podman save -o /tmp/images-${{ github.run_id }}/dev-image.tar localhost/ocserv-modern-dev:latest

      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: dev-image
          path: /tmp/images-${{ github.run_id }}/dev-image.tar
          retention-days: 1

  build-test:
    name: Build Test Image
    runs-on: [self-hosted, linux, x64, oracle-linux]
    needs: build-dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download dev image
        uses: actions/download-artifact@v4
        with:
          name: dev-image
          path: /tmp/images-${{ github.run_id }}

      - name: Load dev image
        run: |
          podman load -i /tmp/images-${{ github.run_id }}/dev-image.tar

      - name: Build test image
        run: |
          cd deploy/podman
          chmod +x scripts/build-test.sh
          IMAGE_NAME=localhost/ocserv-modern-test IMAGE_TAG=latest ./scripts/build-test.sh
        timeout-minutes: 10

      - name: Save test image
        run: |
          podman save -o /tmp/images-${{ github.run_id }}/test-image.tar localhost/ocserv-modern-test:latest

      - name: Upload test image artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-image
          path: /tmp/images-${{ github.run_id }}/test-image.tar
          retention-days: 1

  build-build:
    name: Build Build Image
    runs-on: [self-hosted, linux, x64, oracle-linux]
    needs: verify-setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Clean previous builds
        run: |
          podman rm -f ocserv-modern-build-build || true
          podman rmi -f localhost/ocserv-modern-build:latest || true

      - name: Build build image
        run: |
          cd deploy/podman
          chmod +x scripts/build-build.sh
          IMAGE_NAME=localhost/ocserv-modern-build IMAGE_TAG=latest ./scripts/build-build.sh
        timeout-minutes: 25

      - name: Save build image
        run: |
          mkdir -p /tmp/images-${{ github.run_id }}
          podman save -o /tmp/images-${{ github.run_id }}/build-image.tar localhost/ocserv-modern-build:latest

      - name: Upload build image artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-image
          path: /tmp/images-${{ github.run_id }}/build-image.tar
          retention-days: 1

  build-ci:
    name: Build CI Image
    runs-on: [self-hosted, linux, x64, oracle-linux]
    needs: build-build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build image
        uses: actions/download-artifact@v4
        with:
          name: build-image
          path: /tmp/images-${{ github.run_id }}

      - name: Load build image
        run: |
          podman load -i /tmp/images-${{ github.run_id }}/build-image.tar

      - name: Build CI image
        run: |
          cd deploy/podman
          chmod +x scripts/build-ci.sh
          IMAGE_NAME=localhost/ocserv-modern-ci IMAGE_TAG=latest ./scripts/build-ci.sh
        timeout-minutes: 5

      - name: Save CI image
        run: |
          podman save -o /tmp/images-${{ github.run_id }}/ci-image.tar localhost/ocserv-modern-ci:latest

      - name: Upload CI image artifact
        uses: actions/upload-artifact@v4
        with:
          name: ci-image
          path: /tmp/images-${{ github.run_id }}/ci-image.tar
          retention-days: 1

  test-backends:
    name: Test TLS Backends
    runs-on: [self-hosted, linux, x64, oracle-linux]
    needs: build-dev
    strategy:
      matrix:
        backend: [gnutls, wolfssl]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download dev image
        uses: actions/download-artifact@v4
        with:
          name: dev-image
          path: /tmp/images-${{ github.run_id }}

      - name: Load dev image
        run: |
          podman load -i /tmp/images-${{ github.run_id }}/dev-image.tar

      - name: Compile ${{ matrix.backend }} backend
        run: |
          podman run --rm \
            -v ${{ github.workspace }}:/workspace:Z \
            -w /workspace \
            localhost/ocserv-modern-dev:latest \
            bash -c "make clean && make BACKEND=${{ matrix.backend }} all"
        timeout-minutes: 5

      - name: Run unit tests (${{ matrix.backend }})
        run: |
          podman run --rm \
            -v ${{ github.workspace }}:/workspace:Z \
            -w /workspace \
            localhost/ocserv-modern-dev:latest \
            bash -c "make BACKEND=${{ matrix.backend }} test-unit"
        timeout-minutes: 3

  quick-validate:
    name: Quick Validation
    runs-on: [self-hosted, linux, x64, oracle-linux]
    needs: build-ci
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download CI image
        uses: actions/download-artifact@v4
        with:
          name: ci-image
          path: /tmp/images-${{ github.run_id }}

      - name: Load CI image
        run: |
          podman load -i /tmp/images-${{ github.run_id }}/ci-image.tar

      - name: Run quick validation
        run: |
          podman run --rm \
            -v ${{ github.workspace }}:/workspace:Z \
            localhost/ocserv-modern-ci:latest \
            /usr/local/bin/quick-validate || echo "Quick validate script not found yet"
        timeout-minutes: 5

  run-tests:
    name: Run Tests
    runs-on: [self-hosted, linux, x64, oracle-linux]
    needs: build-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download test image
        uses: actions/download-artifact@v4
        with:
          name: test-image
          path: /tmp/images-${{ github.run_id }}

      - name: Load test image
        run: |
          podman load -i /tmp/images-${{ github.run_id }}/test-image.tar

      - name: Run tests
        run: |
          podman run --rm \
            -v ${{ github.workspace }}:/workspace:Z \
            localhost/ocserv-modern-test:latest \
            /usr/local/bin/run-tests || echo "Test script not found yet"
        timeout-minutes: 10

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results/
          retention-days: 7
          if-no-files-found: ignore

      - name: Upload coverage reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: coverage-reports/
          retention-days: 7
          if-no-files-found: ignore

  cleanup:
    name: Cleanup Build Artifacts
    runs-on: [self-hosted, linux, x64, oracle-linux]
    needs: [test-backends, run-tests, quick-validate]
    if: always()
    steps:
      - name: Clean up temporary files
        run: |
          rm -rf /tmp/images-${{ github.run_id }}
          echo "Cleaned up /tmp/images-${{ github.run_id }}"

      - name: Prune old images
        run: |
          podman image prune -f --filter "until=24h"
          echo "Pruned images older than 24 hours"

  push-images:
    name: Push Images to Registry
    runs-on: [self-hosted, linux, x64, oracle-linux]
    needs: [build-dev, build-test, build-build, build-ci, run-tests]
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all images
        uses: actions/download-artifact@v4
        with:
          path: /tmp/images-${{ github.run_id }}

      - name: Load all images
        run: |
          podman load -i /tmp/images-${{ github.run_id }}/dev-image/dev-image.tar
          podman load -i /tmp/images-${{ github.run_id }}/test-image/test-image.tar
          podman load -i /tmp/images-${{ github.run_id }}/build-image/build-image.tar
          podman load -i /tmp/images-${{ github.run_id }}/ci-image/ci-image.tar

      - name: Log in to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | podman login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push development image
        run: |
          podman tag localhost/ocserv-modern-dev:latest ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}-dev:latest
          podman tag localhost/ocserv-modern-dev:latest ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}-dev:${{ github.sha }}
          podman push ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}-dev:latest
          podman push ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}-dev:${{ github.sha }}

      - name: Push test image
        run: |
          podman tag localhost/ocserv-modern-test:latest ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}-test:latest
          podman push ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}-test:latest

      - name: Push build image
        run: |
          podman tag localhost/ocserv-modern-build:latest ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}-build:latest
          podman push ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}-build:latest

      - name: Push CI image
        run: |
          podman tag localhost/ocserv-modern-ci:latest ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}-ci:latest
          podman push ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}-ci:latest

  security-scan:
    name: Security Scan
    runs-on: [self-hosted, linux, x64, oracle-linux]
    needs: build-dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download dev image
        uses: actions/download-artifact@v4
        with:
          name: dev-image
          path: /tmp/images-${{ github.run_id }}

      - name: Load dev image
        run: |
          podman load -i /tmp/images-${{ github.run_id }}/dev-image.tar

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: localhost/ocserv-modern-dev:latest
          format: 'sarif'
          output: 'trivy-results.sarif'
        continue-on-error: true

      - name: Upload Trivy results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'
        continue-on-error: true
